language: node_js
node_js: stable
script:
  - node base64.js
deploy:
  on:
    branch: master
notifications:
  email:
    recipients:
      - mingwiki@gmail.com
    on_success: change
    on_failure: always
