language: node_js
node_js: stable
script:
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"
  - git config --global push.default simple
  - git remote set-url origin https://${GH_TOKEN}@github.com/mingwiki/proxy.git
  - node base64.js
  - git add list.txt
  - git commit --message "Travis build $TRAVIS_BUILD_NUMBER"
  - git push origin master
notifications:
  email:
    recipients:
      - mingwiki@gmail.com
    on_success: change
    on_failure: always
